/*Suppression des tables*/
DROP TABLE CENTRE_INTERET;
DROP TABLE CONSULTATION;
DROP TABLE UTILISATEUR;

/*Création de la table utilisateur*/
create table UTILISATEUR (
	id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 , INCREMENT BY 1) not null,
	nom varchar(40) not null,
	prenom varchar(40) not null,
	age integer not null,
	mail varchar(150) not null,
	sexe varchar (40) not null,
	CI integer not null,
	constraint pk_utilisateur_id primary key(id)
);

/*Création de la table Consultation*/
create table CONSULTATION(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 , INCREMENT BY 1 ) not null ,
	id_utilisateur_consulte integer not null,
	adresse_ip_visiteur varchar(11) not null,
	date_visite datetime not null,
	constraint pk_consultation_id primary key(id)
);

/*Création de la table Centre_interet*/
create table CENTRE_INTERET(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY  (START WITH 1 , INCREMENT BY 1 ) not null,
	libelle varchar(50) not null,
	constraint pk_centre_interet_id primary key(id)
);


/*Ajout de contraintes*/
alter table CONSULTATION
add constraint fk_consultation_id_utilisateur_consulte foreign key(id_utilisateur_consulte)
				REFERENCES UTILISATEUR(id);
								
alter table UTILISATEUR
add constraint fk_user_CI foreign key(CI)
				REFERENCES CENTRE_INTERET(ID);						


/*Insertion dans la table centre interet*/
INSERT INTO "PUBLIC"."CENTRE_INTERET"
(  "ID", "LIBELLE" )
VALUES ('1', 'Java');

INSERT INTO "PUBLIC"."CENTRE_INTERET"
(  "ID", "LIBELLE" )
VALUES ('2', 'PHP');

INSERT INTO "PUBLIC"."CENTRE_INTERET"
(  "ID", "LIBELLE" )
VALUES ('3', 'C#');

INSERT INTO "PUBLIC"."CENTRE_INTERET"
(  "ID", "LIBELLE" )
VALUES ('4', 'TDD');

INSERT INTO "PUBLIC"."CENTRE_INTERET"
(  "ID", "LIBELLE" )
VALUES ('5', 'Junit');				
				
				
/*Insertion dans la table utilsiateur*/						
INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Goulier', 'Jérémy', '21', 'j.goulier@orange.fr','homme','1');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Olivo', 'Martin', '21', 'martinator@hotmail.fr','homme','2');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Dufour', 'Pierre', '22', 'pierre.dufour@sfr.com', 'homme','3');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Garel', 'Lorraine', '25', 'lorraine.garel@free.fr', 'femme','4');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Lespect', 'Jo', '27', 'j.lespect@orange.fr','homme','1');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Affou', 'Adam', '21', 'adamaffou@orange.fr','homme','1');

INSERT INTO "PUBLIC"."UTILISATEUR"
("NOM", "PRENOM", "AGE", "MAIL", "SEXE", "CI" )
VALUES ('Vautard', 'Florian', '23', 'vf@orange.fr','homme','2');

